name: Cerver Beta Integration

on:
  push:
    branches:
      - '*beta'
      - '!master'
  pull_request:
    branches:
      - '*beta'
      - '!master'

jobs:
  build:
    name: Cerver beta build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install libcurl4-openssl-dev

      - name: gcc make
        run: make TYPE=test
      - name: gcc examples
        run: make TYPE=test examples
      - name: gcc tests
        run: make test
      - name: gcc run tests
        run: bash test/run.sh

      - name: clean
        run: make clean

      - name: g++ make
        run: make TYPE=test CC=g++
      - name: g++ examples
        run: make TYPE=test CC=g++ examples
      - name: g++ tests
        run: make CC=g++ test
      - name: g++ run tests
        run: bash test/run.sh
  
  docker:
    needs: build
    name: Docker build test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.test
          tags: ermiry/cerver:test
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
