name: Cerver Continuous integration

on:
  push:
    branches:
      - '*' 
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Cerver test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make
      - name: examples
        run: make examples
