name: Cerver Continuous Integration

on:
  push:
    branches-ignore:
      - 'master'
      - '*beta'
  pull_request:
    branches-ignore:
      - 'master'
      - '*beta'

jobs:
  build:
    name: Cerver test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get install libcurl4-openssl-dev

      - name: System Information
        run: gcc --version && g++ --version

      - name: gcc make
        run: make
      - name: gcc examples
        run: make examples
      - name: gcc tests
        run: make test
      - name: gcc run tests
        run: bash test/run.sh

      - name: clean
        run: make clean

      - name: g++ make
        run: make CC=g++
      - name: g++ examples
        run: make CC=g++ examples
      - name: g++ tests
        run: make CC=g++ test
      - name: g++ run tests
        run: bash test/run.sh
