name: Cerver Test Builders

on:
  pull_request:
    branches:
      - 'master'
      - '*beta'

jobs:
  build:
    # test builder & buildev images build
    name: Build builder docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read version file
        id: get_version
        run: echo "::set-output name=version::$(cat version.txt)"

      # docker setup
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # buildev
      # build cerver development builder image
      # used to build projects with development cerver libraries
      - name: Build buildev image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.buildev
          tags: ermiry/cerver:${{ steps.get_version.outputs.version }}-buildev
      
      # builder
      # build cerver production builder image
      # used to build projects with production cerver libraries
      - name: Build builder image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.builder
          tags: ermiry/cerver:${{ steps.get_version.outputs.version }}-builder