name: Cerver Continuous Integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Cerver test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gcc make
        run: make
      - name: gcc examples
        run: make examples
      - name: gcc tests
        run: make test
      - name: gcc run tests
        run: bash test.sh

      - name: clean
        run: make clean

      - name: g++ make
        run: make CC=g++
      - name: g++ examples
        run: make CC=g++ examples
      - name: g++ tests
        run: make CC=g++ test
      - name: g++ run tests
        run: bash test.sh
