name: Cerver CMongo Integration

on:
  push:
    branches:
      - 'master'
      - '*beta'

jobs:
  build:
    # build & push ready to use cerver-cmongo images
    name: Build docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read version file
        id: get_version
        run: echo "::set-output name=version::$(cat version.txt)"

      # docker setup
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # login
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # development
      # build cerver & cmongo development image
      # generates an ubuntu based docker with development libraries
      - name: Build and push development image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmongo/Dockerfile.dev
          tags: ermiry/cerver-cmongo:dev-${{ steps.get_version.outputs.version }}
          push: true

      # buildev
      # build cerver & cmongo development builder image
      # used to build projects with development cerver & cmongo libraries
      - name: Build buildev image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmongo/Dockerfile.buildev
          tags: ermiry/cerver-cmongo:buildev-${{ steps.get_version.outputs.version }}
          push: true
      
      # builder
      # build cerver & cmongo production builder image
      # used to build projects with production cerver & cmongo libraries
      - name: Build builder image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmongo/Dockerfile.builder
          tags: ermiry/cerver-cmongo:builder-${{ steps.get_version.outputs.version }}
          push: true

      # production
      # build cerver & cmongo production ready image
      # generates an ubuntu based docker with production libraries
      - name: Build production image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmongo/Dockerfile
          tags: ermiry/cerver-cmongo:${{ steps.get_version.outputs.version }}
          push: true
