name: Cerver Production Integration

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Cerver production build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: gcc DEVELOPMENT='' make
        run: make
      - name: gcc examples
        run: make examples
      - name: gcc tests
        run: make test
      - name: gcc run tests
        run: bash test.sh

      - name: clean
        run: make clean

      - name: g++ DEVELOPMENT='' make
        run: make CC=g++
      - name: g++ examples
        run: make CC=g++ examples
      - name: g++ tests
        run: make CC=g++ test
      - name: g++ run tests
        run: bash test.sh

  docker:
    needs: build
    name: Docker build test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.test
          tags: ermiry/cerver:test
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
