name: Cerver Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Cerver tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get install libcurl4-openssl-dev

      - name: Build Docker Image
        run: docker build -t ermiry/cerver:test -f Dockerfile.test .

      - name: Compile Sources
        run: make TYPE=test COVERAGE=1

      - name: Compile Tests
        run: make TYPE=test COVERAGE=1 test

      - name: Unit Tests
        run: bash test/run.sh

      - name: Web Integration Test
        run: |
          sudo docker run -d --name test --rm -p 8080:8080 ermiry/cerver:test ./bin/web/web
          sleep 2
          sudo docker inspect test --format='{{.State.ExitCode}}'
          ./test/bin/client/web
          sudo docker kill $(sudo docker ps -q)

      - name: Coverage
        run: make coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          flags: unittests
          name: build
          fail_ci_if_error: true
          # verbose: true
