name: Cerver Integration Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Cerver tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t ermiry/cerver:test -f Dockerfile.test .

      - name: Compile Sources
        run: make

      - name: Compile Tests
        run: make test

      - name: Unit Tests
        run: bash test/run.sh

      - name: Ping Integration Test
        run: |
          docker run -d --name test --rm -p 7000:7000 ermiry/cerver:test ./bin/cerver/ping
          sleep 2
          sudo docker inspect test --format='{{.State.ExitCode}}'
          ./test/bin/client/ping
          sudo docker kill $(sudo docker ps -q)

      - name: Packets Integration Test
        run: |
          sudo docker inspect test --format='{{.State.ExitCode}}'
          ./test/bin/client/ping
          sudo docker kill $(sudo docker ps -q)
